"use client";

import Link from "next/link";
import { useState, useTransition } from "react";
import { toast } from "sonner";
import { CheckCircle2Icon } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { PriorityBadge, StatusBadge } from "@/lib/status";
import {
  buildImportPreview,
  parseImportText,
  type ImportPreview,
} from "@/lib/import/parse-import";
import { importTicket } from "@/app/(dashboard)/tickets/actions";

export default function ImportPage() {
  const [text, setText] = useState("");
  const [preview, setPreview] = useState<ImportPreview | null>(null);
  const [imported, setImported] = useState<{ id: string; title: string } | null>(null);
  const [pending, startTransition] = useTransition();

  function buildPreviewFromText(): ImportPreview {
    const parsed = parseImportText(text);
    if ("formatError" in parsed) {
      return {
        valid: false,
        formatError: parsed.formatError,
        ticket: { data: {}, errors: [] },
        testCases: [],
      };
    }
    return buildImportPreview(parsed.json);
  }

  function handlePreview() {
    setPreview(buildPreviewFromText());
  }

  function runImport(data: NonNullable<ImportPreview["data"]>) {
    startTransition(async () => {
      const result = await importTicket(data);
      if (result?.error) {
        toast.error(result.error);
        return;
      }
      toast.success("Ticket imported");
      setImported({ id: result.ticketId!, title: result.title! });
      setText("");
      setPreview(null);
    });
  }

  function handleConfirm() {
    if (!preview?.valid || !preview.data) return;
    runImport(preview.data);
  }

  function handleQuickImport() {
    const built = buildPreviewFromText();
    if (!built.valid || !built.data) {
      setPreview(built);
      toast.error("Fix the errors below before importing.");
      return;
    }
    setPreview(null);
    runImport(built.data);
  }

  function handleImportNew() {
    setImported(null);
  }

  return (
    <div className="flex flex-col gap-4">
      <div>
        <h1 className="text-lg font-semibold">Import Ticket</h1>
        <p className="text-sm text-muted-foreground">
          Paste the JSON payload generated by the AI workflow — a ticket plus
          its test cases.
        </p>
      </div>

      {imported && (
        <Card className="border-green-600/30">
          <CardContent className="flex flex-wrap items-center justify-between gap-3">
            <div className="flex items-center gap-2">
              <CheckCircle2Icon className="size-4 shrink-0 text-green-600 dark:text-green-400" />
              <span className="text-sm">
                Imported <span className="font-medium">{imported.title}</span>
              </span>
            </div>
            <div className="flex items-center gap-2">
              <Button
                variant="outline"
                size="sm"
                nativeButton={false}
                render={<Link href={`/tickets/${imported.id}`} />}
              >
                View ticket
              </Button>
              <Button size="sm" onClick={handleImportNew}>
                Import new ticket
              </Button>
            </div>
          </CardContent>
        </Card>
      )}

      <Card>
        <CardContent className="flex flex-col gap-3">
          <Textarea
            value={text}
            onChange={(e) => setText(e.target.value)}
            placeholder='{"ticket": {...}, "test_cases": [...]}'
            className="min-h-48 font-mono text-xs"
          />
          <div className="flex justify-end gap-2">
            <Button variant="outline" onClick={handlePreview} disabled={!text.trim() || pending}>
              Preview
            </Button>
            <Button onClick={handleQuickImport} disabled={!text.trim() || pending}>
              {pending ? "Importing..." : "Confirm Import"}
            </Button>
          </div>
        </CardContent>
      </Card>

      {preview && (
        <Card>
          <CardHeader>
            <CardTitle className="text-base">Preview</CardTitle>
          </CardHeader>
          <CardContent className="flex flex-col gap-4">
            {preview.formatError && (
              <p className="text-sm text-destructive">{preview.formatError}</p>
            )}

            <div>
              <h3 className="mb-2 text-sm font-medium">Ticket</h3>
              {preview.ticket.errors.length > 0 ? (
                <ul className="list-inside list-disc text-sm text-destructive">
                  {preview.ticket.errors.map((err) => (
                    <li key={err.field}>
                      {err.field}: {err.message}
                    </li>
                  ))}
                </ul>
              ) : (
                <dl className="grid grid-cols-2 gap-x-6 gap-y-1 text-sm sm:grid-cols-3">
                  <div>
                    <dt className="text-muted-foreground">Title</dt>
                    <dd>{String(preview.ticket.data.title ?? "—")}</dd>
                  </div>
                  <div>
                    <dt className="text-muted-foreground">Company</dt>
                    <dd>{String(preview.ticket.data.company ?? "—")}</dd>
                  </div>
                  <div>
                    <dt className="text-muted-foreground">System</dt>
                    <dd>{String(preview.ticket.data.system ?? "—")}</dd>
                  </div>
                  <div>
                    <dt className="text-muted-foreground">Module</dt>
                    <dd>{String(preview.ticket.data.module ?? "—")}</dd>
                  </div>
                  <div>
                    <dt className="text-muted-foreground">Issue Type</dt>
                    <dd>{String(preview.ticket.data.issue_type ?? "—")}</dd>
                  </div>
                  <div>
                    <dt className="text-muted-foreground">Tester</dt>
                    <dd>{String(preview.ticket.data.tester ?? "—")}</dd>
                  </div>
                  <div>
                    <dt className="text-muted-foreground">Dev</dt>
                    <dd>{String(preview.ticket.data.dev ?? "—")}</dd>
                  </div>
                </dl>
              )}
            </div>

            {preview.testCases.length > 0 && (
              <div>
                <h3 className="mb-2 text-sm font-medium">
                  Test Cases ({preview.testCases.length})
                </h3>
                <div className="rounded-xl ring-1 ring-foreground/10">
                  <Table>
                    <TableHeader>
                      <TableRow>
                        <TableHead>TC#</TableHead>
                        <TableHead>Page</TableHead>
                        <TableHead>Priority</TableHead>
                        <TableHead>Status</TableHead>
                        <TableHead>Errors</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {preview.testCases.map((row) => (
                        <TableRow key={row.index}>
                          <TableCell>{String(row.data.tc_number ?? "—")}</TableCell>
                          <TableCell className="text-muted-foreground">
                            {String(row.data.page ?? "—")}
                          </TableCell>
                          <TableCell>
                            {row.data.priority ? (
                              <PriorityBadge priority={row.data.priority} />
                            ) : (
                              "—"
                            )}
                          </TableCell>
                          <TableCell>
                            {row.data.status ? (
                              <StatusBadge status={row.data.status} />
                            ) : (
                              "—"
                            )}
                          </TableCell>
                          <TableCell>
                            {row.errors.length > 0 ? (
                              <span className="text-xs text-destructive">
                                {row.errors
                                  .map((e) => `${e.field}: ${e.message}`)
                                  .join("; ")}
                              </span>
                            ) : (
                              <span className="text-xs text-green-600 dark:text-green-400">
                                OK
                              </span>
                            )}
                          </TableCell>
                        </TableRow>
                      ))}
                    </TableBody>
                  </Table>
                </div>
              </div>
            )}

            <div className="flex justify-end">
              <Button onClick={handleConfirm} disabled={!preview.valid || pending}>
                {pending ? "Importing..." : "Confirm Import"}
              </Button>
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
